### ISSUE TITLE
OLM operatorhubio infinite loop

### ISSUE THREAD

**Issue by jshsp** [CrowdStrike/falcon-operator#107]
Greetings not sure if this should go to the OLM repo but it only appears when installing falcon-operator.
The operatorhubio-catalog pods infinitely loop and never start. 

➜  statefulissue git:(main) ✗ kgp
NAME                                READY   STATUS        RESTARTS   AGE
catalog-operator-765c45774c-qnvnw   1/1     Running       0          3h49m
olm-operator-9bb87877b-sc6rn        1/1     Running       0          3h49m
operatorhubio-catalog-2rh49         0/2     Terminating   0          0s
operatorhubio-catalog-2tfwp         0/2     Terminating   0          2s
operatorhubio-catalog-kf255         0/2     Terminating   0          1s
packageserver-5657dcbc44-895vq      1/1     Running       0          3h47m
packageserver-5657dcbc44-fd2pn      1/1     Running       0          3h47m`

Examples of an error i could grab was:
1)
Pod 'operatorhubio-catalog-gb84h': error 'pods "operatorhubio-catalog-gb84h" not found', but found events.
Events:
```
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  5s    default-scheduler  Successfully assigned olm/operatorhubio-catalog-gb84h to gke-cluster-2-20-default-pool-d4df75be-l0sr
  Normal   Pulled     4s    kubelet            Container image "gcr.io/REDACTED/falcon-container:6.31.0-1409.container.x86_64.Release.US-2" already present on machine
  Normal   Created    4s    kubelet            Created container crowdstrike-falcon-init-container
  Warning  Failed     4s    kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/kubelet/pods/7
f7ea6dd-d50e-44a8-a867-477f055222f8/volumes/kubernetes.io~empty-dir/crowdstrike-falcon-volume" to rootfs at "/tmp/CrowdStrike" caused: stat /var/lib/kubelet/pods/7f7ea6dd-d50e-44a8-a867-477f055222f8/volumes/kubernetes.io~empty-dir/crowdstrike-falcon-volume: no such file o
r directory: unknown`
```

**Comment by redhatrises** [comment]
@isimluk thoughts on this issue?

**Comment by isimluk** [comment]
@redhatrises, I have spent considerable amount of time of time trying to reproduce this, but had no luck.

@jshsp, is there anything particular (I mean non standard) worth mentioning on your cluster? Which version of OLM are you running?

**Comment by jshsp** [comment]
Its all pretty standard - GKE environments - it also happened on different version of kubernetes. 
It was the latest version of OLM at the time which was:
>   version: v0.19.1

**Comment by redhatrises** [comment]
@jshsp Is it still an issue with olm in your environment then?

**Comment by isimluk** [comment]
I managed to get the the reproducer. Although, I got different error, I can see the crash loop.

**Comment by redhatrises** [comment]
Closing as there is no further movement on this, please re-open if the error is still persisting or there are further questions around this.
