### ISSUE TITLE
Support node and pod metrics

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/falcon-operator#15]
We should support gathering the following metrics:

- how many nodes are in the cluster per week, month, and year
- how many pods there are in the cluster per week, month, and year

**Comment by shawndwells** [comment]
Is there a way to detect the average simultaneously running data, versus aggregate?

eg if pods spin up and down, we might show 1,000,0000 unique pods. But in reality only 20,000 might be running simultaneously (and require CrowdStrike subscription).

**Comment by redhatrises** [comment]
Closing this as this is out of scope for the operator's workload to perform.
