### ISSUE TITLE
Has something happened to the falcon-node-sensor:latest repo?

### ISSUE THREAD

**Issue by dmcnaught** [CrowdStrike/falcon-operator#157]
I noticed this error in my cluster. 
Has the access to the falcon-node-sensor:latest changed?
I haven't set a custom node.image in https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/config/samples/falcon_v1alpha1_falconnodesensor.yaml
```
1s          Normal    Pulling            pod/falcon-node-sensor-xbsh5   Pulling image "falcon-node-sensor:latest"
1s          Warning   Failed             pod/falcon-node-sensor-xbsh5   Failed to pull image "falcon-node-sensor:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for falcon-node-sensor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
1s          Warning   Failed             pod/falcon-node-sensor-xbsh5   Error: ErrImagePull
```

**Comment by redhatrises** [comment]
Hello,

This is the default setting which isn't a valid container repo which is why you are seeing that error. You need to configure to point to your repository that contains the sensor.

**Comment by dmcnaught** [comment]
ok, thanks

**Comment by dmcnaught** [comment]
Is there documentation about that part?

**Comment by dmcnaught** [comment]
I don't find anything in the repo about creating the image for the falcon-node-sensor

**Comment by dmcnaught** [comment]
Ah - I found https://github.com/CrowdStrike/Dockerfiles
Maybe I was incorrect in using this repo as the starting point. It was the one we found.
Looks like this would be a better place to start: https://github.com/CrowdStrike/falcon-helm

**Comment by redhatrises** [comment]
> Ah - I found https://github.com/CrowdStrike/Dockerfiles Maybe I was incorrect in using this repo as the starting point. It was the one we found. Looks like this would be a better place to start: https://github.com/CrowdStrike/falcon-helm

Hello,

Yes. Regardless of whether or not you use the helm charts or the operator, you will still have to build and manage the falcon sensor built from https://github.com/CrowdStrike/Dockerfiles. Ultimately, the helm charts will be updated to install this operator.
