### ISSUE TITLE
Support GCP Workload Identity Annotations

### ISSUE THREAD

**Issue by gaahrdner** [CrowdStrike/falcon-operator#190]
I noticed in #172 that the ability to add EKS annotations was added. Could this be done for [GCP Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) as well? This would allow access to Container Registry/Artifact Registry.

Specifically the annotation to the service account looks something like this:

```
metadata:
  annotations:
    iam.gke.io/gcp-service-account:<my-gcp-service-account>@<my-gcp-project>.iam.gserviceaccount.com
```

**Comment by isimluk** [comment]
I should have probably implement generic way how to forward service account annotations. As @RutledgePaulV suggested at some point.
