### ISSUE TITLE
nodesensor unable to connect

### ISSUE THREAD

**Issue by jon-coppin** [CrowdStrike/falcon-operator#221]
Deploying on Openshift 4.10, nodesensors are unable to connect to crowdstrike

Tue Apr 19 18:05:06 2022 Failed to fetch network containment rules: STATUS=0xC0000034 (2306103) [210]
Tue Apr 19 18:05:06 2022 Failed to refresh active rules from userspace (2306103) [588]
Tue Apr 19 18:05:06 2022 Could not enumerate existing rules: STATUS=0xC0000034 (2306103) [382]
Tue Apr 19 18:05:06 2022 NFI wasn't ready: STATUS=0xC0000034 (2306103) [2101]
Tue Apr 19 18:05:06 2022 Failed to allow DNS; proceeding anyway: STATUS=0xC0000034 (2306103) [437]
Tue Apr 19 18:05:06 2022 Unable to resolve address, getaddrinfo returned -11 (2306103) [493]
Tue Apr 19 18:05:06 2022 Unable to connect to ts01-gyr-maverick.cloudsink.net:443 (2306103) [2917]
Tue Apr 19 18:05:06 2022 Connect backoff at maximum limit (2306103) [3306]
Tue Apr 19 18:09:22 2022 Could not retrieve DisableProxy value: STATUS=0xC0000225 (2306103) [1813]
Tue Apr 19 18:09:22 2022 Unable to get application proxy host from simple store: STATUS=0xC0000225 (2306103) [1866]
Tue Apr 19 18:09:22 2022 Couldn't open file /proc/falcon_nf_netcontain/rules: ERRNO=2 () (2306103) [324]
Tue Apr 19 18:09:22 2022 Failed to fetch rules from proc: STATUS=0xC0000034

**Comment by isimluk** [comment]
@jon-coppin, this may be an indication that the sensor is not able to CrowdStrike cloud. Possibly the DNS name of `ts01-gyr-maverick.cloudsink.net`. What I would do is to run some dns resolver within a small pod on this address to verify the networking is fine. Then I would review any networking software / dns filtering that may be interfering. Lastly, I would advocate for opening support case with CrowdStrike. This does not seem to be issue related with the operator, rather with the sensor itself.
