### ISSUE TITLE
Node sensor: Support deployment without client_id/client_secret with imageOverride and CIDOverride

### ISSUE THREAD

**Issue by isimluk** [CrowdStrike/falcon-operator#228]
That may be useful in certain hardened networking environments that do not allow for api access.

**Comment by redhatrises** [comment]
We already have the `image` and `cid` fields so don't think that we need to create new fields. Probably just need to check if `cid` or `image` is set and default to those over using client_id/_secret.

**Comment by isimluk** [comment]
Right. The override mechanism is present and working. What we need to make sure is that falcon-operator won't try to connect to API, if the overrides are present.
