### ISSUE TITLE
Need to be able to upload custom CAs to connect to external registries

### ISSUE THREAD

**Issue by domdepasquale** [CrowdStrike/falcon-operator#239]
The `--registry-certs` option https://github.com/CrowdStrike/falcon-operator/blob/main/pkg/falcon_container_deployer/job.go#L149 is current coded to use the CA for internal K8s API connectivity:
https://github.com/CrowdStrike/falcon-operator/blob/main/pkg/registry/certificate.go

Instead it should be used to specify a ConfigMap/Secret that will get mounted in the Injector's CAPath.

**Comment by isimluk** [comment]
What is the end-result?


Two thoughts with regards to this:
 - User can still override `--registry-certs` in their custom `FalconContainer` resource if they choose to
 - If the operator has the `/var/run/secrets/kubernetes.io/serviceaccount/` path, it means that kubernetes has mounted that path to the operator automatically. If that is the case, chances are pretty high that the same path will get mounted to the injector. I.e. on clusters with properly configured custom CA, the pods will already have access to the custom CA and there is no need to double mount the same certificate.

**Comment by domdepasquale** [comment]
I took a look at the `FalconContainer` CRD and didn't see where the option was defined.

Perhaps it'd be better if I wrote a user-story:

My application image, say it's wildfly18, lives in my local repository (Nexus). It is signed with a self-signed cert. According to the injector documentation, I should mount a directory with my CA crt:
```
-registry-certs string
    	Path to a directory containing all registry CA certificates. A CA certificate file name needs to be a valid config map key, and have the extension ".crt"
```

**Comment by isimluk** [comment]
With regards to the above user story, I would be curious to learn how that CA certificate is distributed to the kubernetes nodes. These nodes need to be able to fetch from the said nexus registry as well. These nodes are probably configured somehow in kubernetes. Is there any way falcon operator may re-use that method? Often times, the answer leads towards discovery of the certificate mounted under  /var/run/secrets/kubernetes.io/serviceaccount/ path.

If not (haven't yet seen this case), then user should be able to use:
```
spec:
 installer_args:
       - '--registry-certs=STRING'
```

**Comment by domdepasquale** [comment]
I'll need to ask internally. I was under the assumption that the _injector itself_ needed access to the CA cert for scanning image metadata (e.g. the entrypoint), not to have Kubernetes pull the image into the cluster.

**Comment by domdepasquale** [comment]
FWIW, this didn't work on Minikube. (Not sure I would consider it a valid environment to test on).
Proceedure:

1. Started minikube with `minikube start --embed-certs` after adding my CAs to `~/.minikube/certs`
1. Verified that I could 
   1. See the certs inside /etc/ssl/certs/ within minikube
   1. Deploy a test app from my registry
1. Attempted to inject a deployment via operator installed injector
1. Failure logs (with redactions):

```
time="2022-06-13T18:09:12Z" level=error msg="Failed to handle webhook request" error="Failed to retrieve image details for \"[REDACTED]/nginx-unprivileged:stable\" in container \"nginx\" in pod \"default/\": Failed to get the image config/digest for \"[REDACTED]/nginx-unprivileged:stable\" on \"[REDACTED]\": pinging container registry [REDACTED]: Get \"https://[REDACTED]\": x509: certificate signed by unknown authority" id=[REDACTED] namespace=default
```

We can talk about this when our times alight better if that's ok.

**Comment by domdepasquale** [comment]
Fixed by https://github.com/CrowdStrike/falcon-operator/pull/305
