### ISSUE TITLE
RBAC role least privilege

### ISSUE THREAD

**Issue by dbaribeault** [CrowdStrike/falcon-operator#281]
We would like to request better separation between the rbac required to use the node sensor vs the container sensor (with the latter requiring much more privileges such as webhooks, secrets, etc). We’d expect that the privileges needed to run the operator for just the node sensor would be very similar to that of deploying the Helm chart for just the sensor (just podsecuritypolicy access to the falcon-specific policy).

**Comment by redhatrises** [comment]
Hello,

Can you be more specific here? There already is separate RBAC for the node sensor vs the pod sensor. The node sensor runs privileged and the container sensor only needs to run with PTRACE and anyuid.

**Comment by tbennett0** [comment]
@redhatrises the operator looks like despite whether you plan to run the container sensor, it requires full permissions on the objects @dbaribeault listed. Is that right?

I tried looking at the Kustomize layout to see if we could configure it, but all of the rbac for the operator is in one file. In most clusters, we won't want to use the container sensor custom resource, so adding the RBAC for that gives the operator a very high level of permission that it doesn't need.

**Comment by redhatrises** [comment]
Closing this as there are more resources being added to the operator which encompasses these permissions, and the operator's permissions are based on all the resources that it can deploy vs what is actually deployed. In general, operators and their resources are moving to be more globally scoped.
