### ISSUE TITLE
Falcon Node Sensor on GKE Container-Optimized OS fails on read-only file system

### ISSUE THREAD

**Issue by cpretzer** [CrowdStrike/falcon-operator#289]
I deployed the Falcon Operator (without the OLM operator) and Falcon Node Sensor following the directions [here](https://github.com/CrowdStrike/falcon-operator) and [here](https://github.com/CrowdStrike/falcon-operator/tree/main/docs/node).

When the Node Sensor DaemonSet starts, the init-falconstore container fails because it attempts to write to `/opt` which is [read-only](https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem) in Container-Optimized OS.

Is this a known issue? 

Are there plans to support Container-Optimized OS?

_Error Message_
` OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: mkdir /opt/CrowdStrike: read-only file system: unknown`

**Comment by redhatrises** [comment]
Closing this since the node sensor is unsupported on GCOS atm. If there are roadmap questions around sensor support for specific OSes, a CS support ticket should be opened or the account rep can provide such information. Please re-open if there are further questions around this issue.
