### ISSUE TITLE
Manager log timestamps are in scientific notation

### ISSUE THREAD

**Issue by evanstoner** [CrowdStrike/falcon-operator#411]
This makes determining when things actually happened difficult.

```
1.6910074478039277e+09 INFO version operator {"version": "0.8.1-certified"}
1.6910074478039649e+09 INFO version go {"version": "go1.18.10 linux/amd64"}
1.6910074478039713e+09 INFO setup setting up manager to watch resources {"watchNamespace": ""}
```

Human-friendly preference would be something like `YYYY-MM-DD HH:MM:SS.sss`.

**Comment by redhatrises** [comment]
This is actually the default and production format for datetime stamps (epoch) for k8s and the controller-runtime. This also allows logging utilities to easily convert datetime to what their users want, so I am hesitant to change the default for these reasons. However, all is not lost, and you should be able to change this for your deployment if you so choose to by setting the arg to your operator's deployment:

```
- '--zap-time-encoding=iso8601'
```
Encoding can be `(one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano')`

I believe (haven't tested) that you can also make this change in the subscription.yaml. See https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md for some examples.

**Comment by evanstoner** [comment]
For OpenShift, setting args on the Deployment doesn't work since it's managed by OLM, which immediately restores the original args.

Setting `config.env` on the Subscription does propagate the `ARGS` env var down to the Deployment/Pod/container, but it doesn't actually work to configure the command line args of the manager since the container/manager doesn't do anything with `ARGS`.

At any rate, I'm fine to close as wontfix, unless you want to add support for arbitrary manager args via env var.
