### ISSUE TITLE
Tolerate OpenShift infra nodes

### ISSUE THREAD

**Issue by evanstoner** [CrowdStrike/falcon-operator#459]
Infra nodes can be used in self-managed or SRE-managed OpenShift clusters. They are worker nodes with a `node-role.kubernetes.io/infra` label and a `node-role.kubernetes.io/infra` NoSchedule taint. We should tolerate this taint, like we already tolerate `master` and `control-plane`, to provide full cluster protection out of the box.

Example in ROSA: https://console-openshift-console.apps.estoner412.r4al.p1.openshiftapps.com/k8s/ns/openshift-machine-api/machine.openshift.io~v1beta1~MachineSet/estoner412-hlwr4-infra-us-west-1a/yaml

Docs: https://docs.openshift.com/container-platform/4.14/machine_management/creating-infrastructure-machinesets.html

**Comment by redhatrises** [comment]
@evanstoner are you wanting the infra label to be a toleration by default so that it will automatically be added?

**Comment by evanstoner** [comment]
Yes, tolerate infra label by default. This way we will deploy to all standard tainted node types by default.
