### ISSUE TITLE
[Feature Request]An easy way to support  multi-architecture clusters

### ISSUE THREAD

**Issue by oleksiytsyban** [CrowdStrike/falcon-operator#521]
I have discovered a straightforward method for supporting multi-architecture EKS clusters with the falcon-operator. I have uploaded the sensor image in both amd64 and aarch64 versions to my internal repository under a single tag, following the instructions provided here: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/. I then configured FalconNodeSensor node.image with that tag. As a result, the DaemonSet now deploys the sensor to both amd64 and arm64 nodes.

Is it possible to create the same tags in the Crowdstrike repository? This would eliminate the need for manually uploading images to my local repository.

**Comment by redhatrises** [comment]
Hello,

Thank you for opening this, and I agree that multiarch container images are warranted. However, this repo has no control over the CrowdStrike registry as it focuses solely on the operator. Please contact your CS representative or open a support case with CS to help solve this issue. Thanks!
