### ISSUE TITLE
Admission controller service account permissions in OpenShift

### ISSUE THREAD

**Issue by tarexveff** [CrowdStrike/falcon-operator#542]
Creating an instance of the admission controller via Operator on OpenShift 4.13 resulted in a crashLoop of both admission controller pods with the error:  

"Failed to read webhook metadata" "error"="[validatingwebhookconfigurations.admissionregistration.k8s.io](http://validatingwebhookconfigurations.admissionregistration.k8s.io/) is forbidden: User \"system:serviceaccount:falcon-admission:falcon-operator-admission-controller\" cannot list resource \"validatingwebhookconfigurations\" in API group \"[admissionregistration.k8s.io](http://admissionregistration.k8s.io/)\" at the cluster scope""

I believe I followed the instructions correctly, and I don't recall seeing steps to add other role bindings to the service account.  Thanks!

@evanstoner

**Comment by redhatrises** [comment]
Thanks for opening this. The fixes are already merged into the main branch which the next release will resolve should resolve this problem.

**Comment by tarexveff** [comment]
Thank you!

**Comment by coolhome** [comment]
@redhatrises is there any release scheduled for this?

**Comment by redhatrises** [comment]
The certified version 1.0.1 has been released and is available via the openshift console.
