### ISSUE TITLE
OpenShift 4.14 install

### ISSUE THREAD

**Issue by tammyandlee** [CrowdStrike/falcon-operator#551]
The operator does not complete the install as it's looking for some specific service accounts and permissions on those services account within the falcon-operator namespace.

Is there a prereq doc hidden away some place?

Thanks!

**Comment by redhatrises** [comment]
Please make sure that the namespace, any clusterrole/clusterrolebinding, and CRD is removed before attempting to use the latest certified operator.

**Comment by tammyandlee** [comment]
That was it thanks!

**Comment by tammyandlee** [comment]
When I try to put any vaules in the operator I get a pop up that says not found and a box with no indication as to what was not found :(

**Comment by evanstoner** [comment]
@tammyandlee This appears to be an OpenShift bug. Please just refresh the OpenShift console and try to install again. I ran into it this week.

**Comment by redhatrises** [comment]
Closing this as there doesn't seem to be any further movement. Please re-open if necessary.
