### ISSUE TITLE
Support Windows Nodes

### ISSUE THREAD

**Issue by bernhardloos** [CrowdStrike/falcon-operator#555]
I'm aware that this isn't going to be easy and might even be completely out of scope, but it would be really useful for people running clusters with Windows nodes.

**Comment by redhatrises** [comment]
@bernhardloos agree. Windows support is limited to what the sensor supports today. So while the operator may at some point deploy to windows nodes, it would be best to open a feature request in the Ideas portal in the falcon console requesting windows sensor support for k8s nodes as that is really what needs to support windows nodes before the operator would even be able to do anything.
