### ISSUE TITLE
Falcon API customer ID validation

### ISSUE THREAD

**Issue by sivanov-nuodb** [CrowdStrike/falcon-operator#558]
Unable to supply CrowdStrike Falcon customer ID (masked in the error below) in the FalconNodeSensor custom resource.

```
FalconNodeSensor.falcon.crowdstrike.com "falcon-node-sensor" is invalid: spec.falcon.cid: Invalid value: "3468aaaaaaaaaaaaaaaaaaaaaaaaaaaa": spec.falcon.cid in body should match '^[0-9a-fA-F]{32}-[0-9a-fA-F]{2}$'
```

Falcon operator - v1.0.1
EKS v1.29.4-eks-036c24b

**Comment by redhatrises** [comment]
Hello,

Looks like you are missing the checksum. Please make sure to add it.

**Comment by sivanov-nuodb** [comment]
I was looking into the Falcon operator API description but there is no information on how the CID should be obtained. I'm obtaining the CID from the CrowdStrike Falcon Console UI and it doesn't contain the 2 extra chars (checksum).

**Comment by redhatrises** [comment]
You need to get it from the sensors download page.

**Comment by sivanov-nuodb** [comment]
Thank you for the info!
This is the correct URL - https://falcon.crowdstrike.com/hosts/sensor-downloads.
