### ISSUE TITLE
OpenShift 4.14 Error creating: pods "falcon-node-sensor-" is forbidden: unable to validate against any security context constraint:

### ISSUE THREAD

**Issue by tammyandlee** [CrowdStrike/falcon-operator#563]
Getting this new error with the 1.0.1 Operator
Error creating: pods "falcon-node-sensor-" is forbidden: unable to validate against any security context constraint:

Thanks,
Lee

**Comment by tammyandlee** [comment]
Doing this fixed it.
oc delete $(oc get clusterrole,clusterrolebinding -l crowdstrike.com/created-by=falcon-operator) -o name)

**Comment by redhatrises** [comment]
IIRC this has been documented at https://github.com/CrowdStrike/falcon-operator/tree/main/docs/deployment/openshift#uninstall-the-operator-1. Closing as there doesn't seem to be any further action to take.
