### ISSUE TITLE
Opeshift 4.14 unable to deploy FalconNodeSensor

### ISSUE THREAD

**Issue by siwyroot** [CrowdStrike/falcon-operator#564]
Hello, I'm trying to deploy FalconNodeSensor on OpenShift 4.14, operator installed ok but I cannot create FalconNodeSensor as I get strange error: Not Found. Latest version of operator from OperatorHub 

![image](https://github.com/user-attachments/assets/55ed69b2-083a-4fab-bcd6-7005884fe179)

![image](https://github.com/user-attachments/assets/12bc61a2-373b-467e-b442-319151915b82)

**Comment by n00bsi** [comment]
have a similar problem

```
$ ./oc get ns | grep -i falc
$ 

```

Install Version 1.0.1 at OpenShift 4.15.20 hang
did try under previous version 4.15.17 too... the same

![CrowdStrike_Install_on_OpenShift_4_15_20_part0](https://github.com/user-attachments/assets/d4c10bd9-6b91-4292-9b68-564a65db9f99)

![CrowdStrike_Install_on_OpenShift_4_15_20_part0_1](https://github.com/user-attachments/assets/a5cc430b-878a-4a9e-a572-1208b9628b4c)
![CrowdStrike_Install_on_OpenShift_4_15_20_part0_2](https://github.com/user-attachments/assets/a8a5916c-bcd1-4b68-9236-afe8398bd442)


![CrowdStrike_Install_on_OpenShift_4_15_17](https://github.com/user-attachments/assets/88e70f17-066c-4c1d-8af3-aa22d84c39fc)

![CrowdStrike_Install_on_OpenShift_4_15_17_part2](https://github.com/user-attachments/assets/98b10db9-1875-4b57-9b34-4b8c13b63ee6)

![CrowdStrike_Install_on_OpenShift_4_15_20_part3](https://github.com/user-attachments/assets/55107e1f-d25b-4d7e-a9a7-44f9bb2bfddf)

How to fix this?

**Comment by siwyroot** [comment]
@n00bsi to fix this:
1. Uninstall operator
2. delete all crds with falcon in name
3. delete permission related objects oc delete $(oc get clusterrole,clusterrolebinding -l crowdstrike.com/created-by=falcon-operator -o name)
4. Depending on your OS you have to delete  ~/.kube/config if you are using flux/argocd restart pods that apply yamls
5. Reinstall operator, not you can apply node sensor via cmd (should work via UI) pods will start in different namespace now (falson-system) which will be created by operator

**Comment by redhatrises** [comment]
Assuming that the resources where cleanup before the operator was uninstalled, there is an issue in OpenShift where the resources are not always cleaned up internally in a timely manner which requires you to wait for a while for the kube api to cleanup delete resources internally in openshift before it will allow the operator to work. Also you must clean up all the resources on the cluster. See https://github.com/CrowdStrike/falcon-operator/tree/main/docs/deployment/openshift#uninstall-the-operator-1

**Comment by evanstoner** [comment]
Looks like the issue was resolved for everyone, closing. The OpenShift cleanup steps were improved in #554.
