### ISSUE TITLE
Install Guide Link in CSV Is Path'd Incorrectly

### ISSUE THREAD

**Issue by acornett21** [CrowdStrike/falcon-operator#584]
## Problem
The install guides link in the CSV, points to this repo as a relative path, instead of a remote path. When the CSV is rendered in a cluster, this makes it seem that the guide is hosted at a route in the cluster, which it is not, and errors when a user clicks on it.

## Solution
Point the link to an absolute (http) path either in this repo or on a CrowdStrike website.

## Link to Code
https://github.com/CrowdStrike/falcon-operator/blob/main/bundle/manifests/falcon-operator.clusterserviceversion.yaml#L823

**Comment by evanstoner** [comment]
Thanks @acornett21 ! I think I fixed that once in the generated manifest but not in the base, so it got overwritten. This should fix it for good.
